[package]
name = "sqrt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"

[dependencies.malachite]
version = "0.6.1"
default-features = false
features = ["malachite-nz", "naturals_and_integers"]
